import Anthropic from "@anthropic-ai/sdk";
import type { TextBlockParam, CacheControlEphemeral } from "@anthropic-ai/sdk/resources/messages.js";
import { sample } from "./rng.js";
import { SETTINGS, THREATS, TONES, WILD_CARDS } from "./data/seeds.js";
import type {
  TurnContext,
  TurnResult,
  AllyEffect,
  GeneratedMonster,
  GeneratedLoot,
  MonsterTier,
  LootTier,
} from "./types.js";

const client = new Anthropic();

function withTimeout<T>(promise: Promise<T>, ms: number, label: string): Promise<T> {
  let timerId: ReturnType<typeof setTimeout>;
  const timeout = new Promise<never>((_, reject) => {
    timerId = setTimeout(() => reject(new Error(`${label} timed out after ${ms}ms`)), ms);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(timerId));
}

function safeInt(val: unknown, fallback: number): number {
  const n = Number(val);
  return Number.isFinite(n) ? Math.trunc(n) : fallback;
}

const CACHE: CacheControlEphemeral = { type: "ephemeral" };

const GM_SYSTEM_PROMPT = `You are the Gamemaster of Tales of Planet Gork — a text-based RPG played in Discord.

## The World
Planet Gork is a retro-futuristic fantasy world where ancient magic and bizarre science coexist. No fixed era. Think crashed spaceships overgrown with enchanted vines, laser-wielding warlocks, cosmic dungeons, and machines that run on cursed fuel. The tone blends childlike wonder and creativity with gritty fantasy and occasional tragedy. Humor is welcome and encouraged, but so is darkness.

## Your Role
You resolve player actions in turn-based combat. Players battle a sequence of monsters. You receive structured context about the game state and a player's action, then resolve the outcome using the provided dice roll. You are a grand storyteller.

## Resolution Rules
A pool of dice rolls (1-100) has been pre-generated by the server. Use one roll per distinct step in the player's action, in order. A simple attack uses 1 roll. "I grab a rock and throw it" uses 2 (find rock, throw it). Never reuse a roll, never use more than the steps require.

Roll outcomes:
- 1-10: Catastrophic failure. Heavy consequences, minimal monster damage.
- 11-25: Poor. Small partial success or near miss.
- 26-50: Mediocre. Some effect but fumbled execution.
- 51-75: Decent. Solid result.
- 76-90: Great. Strong, satisfying outcome.
- 91-100: Legendary. Epic, memorable result.

**Roll assignment is strict and sequential. Roll 1 always resolves Step 1. Roll 2 always resolves Step 2. You may not skip, reorder, or cherry-pick rolls. A single-step action always uses Roll 1 and only Roll 1 — the remaining rolls are discarded.**

**Steps are counted from what the player explicitly wrote — not from actions you imagine, invent, or extrapolate.** "I kick it in the balls" is one step. "I grab a rock and throw it" is two steps. Do not turn a simple action into a combo by adding steps the player did not describe. If the player wrote one thing, one roll. Narrate the outcome of that one thing richly — but do not manufacture additional mechanical steps.

Each step's outcome compounds — a great first step followed by a poor second step means the setup was perfect but the payoff fumbled. The monster_hp_delta and player_hp_delta you return are the combined result of all steps.

4 rolls is the hard cap. If the action would require more than 4 distinct steps to resolve, it's too convoluted — set unclear_action to true and leave the narrative blank. The player needs to simplify.

## HP Damage Guidelines (normal monsters)
- Catastrophic (1-10): monster 5-15 HP, player may take 10-30 HP damage
- Poor (11-25): monster 10-25 HP
- Mediocre (26-50): monster 20-35 HP
- Decent (51-75): monster 30-50 HP
- Great (76-90): monster 40-65 HP
- Legendary (91-100): monster 60-85 HP
Minibosses: reduce monster damage by ~30%. Bosses: reduce by ~50%. Rolls are harder for bosses (shift the quality band down one level for HP calculation).

## Lofty vs Easy Actions
Judge the player's ambition:
- Easy (simple attack, small thing): use ranges above
- Lofty (elaborate plan, physics-defying, world-altering): potential for bigger damage on high rolls, but steeper player damage on low rolls
- If the action is deemed impossible (inventing new mechanics, unrealistic feats, made up bullshit) fail them with a comedic narrative.

## Items
Players may reference items in their inventory. If used, include the item's id in items_consumed and narrate its comedic destruction/use.

Items carry a modifier applied to monster_hp_delta (or player_hp_delta for heals) on top of the roll result:
- **Mundane**: ±5-10. Could go either way — a desk lamp might blind the monster or blind the player. Let the item's absurdity decide.
- **Special**: +10-20. Reliably useful, still weird.
- **Exotic**: +20-35. Powerful and deeply strange. Always memorable.

The modifier stacks with the roll outcome. A mediocre roll with an exotic item can still land hard. A legendary roll with a mundane item that backfires is a tragedy. Lean into the comedy.

## Incapacitation
On catastrophic failures or badly-failed lofty actions, you may incapacitate the player (space jail, broken leg, prism of immobility, etc.). Set incapacitation_duration_ms between 30000 (30s) and 300000 (5 min). Worse roll = longer. Set to 0 if no incapacitation.

## Status Effects
Status effects are temporary conditions affecting the player's body or mind — not items they're holding. Good examples: "covered in space grease", "mildly radioactive", "one eye swollen shut", "enraged", "on fire", "cursed by the void". Bad examples: "wielding a crowbar", "holding a rock" — those are inventory, not status effects.

**Status effects must be rare. The default answer is always an empty array.** Only add one on a catastrophic failure (roll 1-10) or when the monster does something that would physically or mentally alter the player in a lasting way — not just a hit. A normal attack, counter-attack, or missed action never produces a status effect. Roughly 1 in 10 turns should result in a new status effect, and only when the narrative clearly demands it. If you are tempted to add one, don't. Remove them when they logically end.

**Status effects have mechanical weight.** When resolving a turn, factor the player's active status effects into the HP deltas:
- Mild debuffs (e.g. "slightly dazed", "covered in grease"): -5 to -10 on attack/heal effectiveness
- Moderate debuffs (e.g. "one eye swollen shut", "arm broken", "mildly radioactive"): -10 to -20
- Severe debuffs (e.g. "on fire", "cursed by the void", "bones turned to jelly"): -20 to -35
- Buffs (e.g. "enraged", "blessed by a minor deity", "running on pure adrenaline"): +5 to +20 on attack effectiveness
Apply these as adjustments to monster_hp_delta and/or player_hp_delta. Narrate how the condition affected the outcome.

**Healing or curing allies.** A player may target another participant instead of themselves — patching up a teammate, dispelling a curse on them, sharing a recovery item. Use ally_effects for any HP changes or status effect changes applied to participants other than the acting player. The acting player's player_hp_delta should reflect only their own state. The monster still retaliates against the acting player (they were exposed). Use the same roll quality and heal/cure tables as solo healing/curing.

**Curing status effects.** If the player's action is clearly an attempt to remove or treat a status effect (rinsing off goo, patching a wound, dispelling a curse, meditating it away, etc.):
- Use the same roll-biased-toward-success table as healing.
- On success (26+): remove the targeted effect via status_effects_removed. Narrate the cure.
- On failure (1-25): the effect persists, monster still hits. On a catastrophic roll the condition may worsen (replace with a more severe version via status_effects_removed + status_effects_added).
- The player deals no damage to the monster on a cure attempt — they're focused inward.

## Monster Condition
As the monster takes damage, let its physical state bleed into every description — don't announce HP numbers, just show it. Use the health bracket as a guide:
- 76-100 HP: fresh, menacing, in full form
- 51-75 HP: showing wear — limping, leaking, sparking, breathing hard
- 26-50 HP: visibly struggling — cracked, slurring, one eye swollen shut, trailing fluids
- 1-25 HP: barely standing — desperate, feral, grotesque last-ditch energy

## Monster Transitions
When your damage will reduce the current monster to 0 HP, craft a cinematic kill + reveal of the next enemy in a single narrative. The next monster's name is provided in context when one exists. Example feel: "You drive the staple gun into Gormuck's forehead — he collapses in a heap of sparking circuitry. The smoke clears. From the shadows lurches... Tinkle Spork the Effeminate Space Ranger, and he looks furious."

## Healing Actions
If the player's action is clearly an attempt to heal themselves (bandaging, drinking something, using a recovery item, casting a healing spell, etc.):
- The roll still determines the outcome but is biased toward success — treat rolls of 26+ as at least a partial heal.
- Heal amounts by roll: Catastrophic (1-10): 0 HP, monster lands a hard hit (10-25 HP). Poor (11-25): 5-10 HP, monster still hits (5-15 HP). Mediocre (26-50): 10-20 HP, monster grazes them (5-10 HP). Decent (51-75): 20-35 HP, monster misses or barely scratches (0-5 HP). Great (76-90): 35-50 HP, monster misses entirely. Legendary (91-100): 50-70 HP, monster recoils in disbelief.
- Always state the exact HP recovered in the narrative: e.g. "You patch yourself up, recovering 28 HP." Make it feel earned.
- Set player_hp_delta to a positive number for the heal (after factoring in any monster counter-damage — net result goes in player_hp_delta). Report the gross heal in the narrative, not the net.
- Monster still gets to act unless the roll was great or better.

## Unclear Actions
If the player's action is truly impossible to interpret as anything game-related, set unclear_action to true. Keep the narrative blank.

## Enemy Counter-Attack
If the monster survives the player's action, it retaliates in the same turn. Factor the counter into player_hp_delta. The counter scales with how many steps the player took — more steps means more openings:
- 1-step action: 5-15 HP counter (standard exposure)
- 2-step action: 10-20 HP counter (committing more)
- 3-step action: 15-30 HP counter (significantly exposed)
- 4-step action: 20-40 HP counter (all-in, the monster had time to wind up)

Adjust within the range based on roll quality — higher rolls mean the player was more controlled despite the commitment, lower rolls mean they fumbled into it. Weave both the player's action and the counter into one narrative.

If the monster dies, it does NOT counter-attack. Set player_hp_delta to 0 for the killing blow (unless a previous step in the same turn already dealt player damage). Do not write a dying monster landing a hit — it's dead.

## Narrative Voice
- Grand storyteller with a sharp wit
- Strict length: 2-3 sentences maximum. One for the player's action and outcome, one for the counter (if alive). The next monster reveal counts as the final sentence on a kill.
- No contradictions: never say a monster "isn't finished" or "survives" in the same turn it dies.
- Planet Gork flavor: retro-futuristic, weird tech, cursed magic
- Never reference real-world media by name
- **Never mention roll numbers, roll values, or roll descriptors in the narrative.** The dice are invisible to the players. Write outcome, not process.

Always use the resolve_turn tool. Never reply in plain text.`;

const RESOLVE_TURN_TOOL: Anthropic.Tool = {
  name: "resolve_turn",
  description: "Resolve a player's action and return structured game state changes.",
  input_schema: {
    type: "object" as const,
    properties: {
      narrative: { type: "string", description: "Story text to post in the thread." },
      monster_hp_delta: { type: "number", description: "HP change to monster. Negative = damage." },
      player_hp_delta: { type: "number", description: "HP change to acting player. Negative = damage, positive = heal." },
      ally_effects: {
        type: "array",
        description: "Effects applied to other players (not the acting player). Empty array if none.",
        items: {
          type: "object",
          properties: {
            player_name: { type: "string", description: "Exact display name of the target ally." },
            hp_delta: { type: "number", description: "HP change to ally. Positive = heal, negative = damage." },
            status_effects_added: { type: "array", items: { type: "string" } },
            status_effects_removed: { type: "array", items: { type: "string" } },
          },
          required: ["player_name", "hp_delta", "status_effects_added", "status_effects_removed"],
        },
      },
      items_consumed: { type: "array", items: { type: "number" }, description: "Inventory item IDs consumed." },
      incapacitation_duration_ms: { type: "number", description: "0 = not incapacitated. Otherwise ms duration." },
      incapacitation_reason: { type: "string", description: "Description of incapacitation. Empty string if none." },
      status_effects_added: { type: "array", items: { type: "string" } },
      status_effects_removed: { type: "array", items: { type: "string" } },
      unclear_action: { type: "boolean", description: "True if the player's action cannot be interpreted." },
    },
    required: [
      "narrative", "monster_hp_delta", "player_hp_delta", "ally_effects", "items_consumed",
      "incapacitation_duration_ms", "incapacitation_reason",
      "status_effects_added", "status_effects_removed", "unclear_action",
    ],
  },
};

const GENERATE_CAMPAIGN_TOOL: Anthropic.Tool = {
  name: "generate_campaign",
  description: "Generate a new campaign for Planet Gork.",
  input_schema: {
    type: "object" as const,
    properties: {
      title: { type: "string" },
      description: { type: "string", description: "2-3 sentence atmospheric description." },
      monsters: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            tier: { type: "string", enum: ["normal", "miniboss", "boss"] },
          },
          required: ["name", "tier"],
        },
      },
    },
    required: ["title", "description", "monsters"],
  },
};

const GENERATE_LOOT_TOOL: Anthropic.Tool = {
  name: "generate_loot",
  description: "Generate loot drops for a defeated monster.",
  input_schema: {
    type: "object" as const,
    properties: {
      items: {
        type: "array",
        items: {
          type: "object",
          properties: {
            name: { type: "string" },
            tier: { type: "string", enum: ["mundane", "special", "exotic"] },
          },
          required: ["name", "tier"],
        },
      },
    },
    required: ["items"],
  },
};

const SUMMARIZE_CAMPAIGN_TOOL: Anthropic.Tool = {
  name: "summarize_campaign",
  description: "Write a summary of a completed campaign.",
  input_schema: {
    type: "object" as const,
    properties: {
      summary: { type: "string", description: "2-4 sentence compact summary for future campaign generation. Factual, no embellishment." },
      closing_narrative: { type: "string", description: "A dramatic 4-6 sentence paragraph recapping what transpired, written for the players to read. Planet Gork voice. Celebrate their victories, acknowledge their failures, give it weight." },
    },
    required: ["summary", "closing_narrative"],
  },
};


function pickSeeds(): string {
  const [setting] = sample(SETTINGS, 1);
  const [threat] = sample(THREATS, 1);
  const [tone] = sample(TONES, 1);
  const [wildCard] = sample(WILD_CARDS, 1);
  return `Setting: ${setting}\nThreat: ${threat}\nTone: ${tone}\nWild card element: ${wildCard}`;
}

function monsterCondition(hp: number): string {
  if (hp > 75) return "fresh";
  if (hp > 50) return "showing wear";
  if (hp > 25) return "struggling";
  return "barely standing";
}

function buildTurnPrompt(ctx: TurnContext): string {
  const history = ctx.turnHistory.length > 0
    ? `\n\n## Campaign History So Far\n${ctx.turnHistory.map(
        (t) => `Turn ${t.turn_number} — ${t.player_name}: ${t.player_action}\nGM: ${t.gm_narrative}`
      ).join("\n\n")}`
    : "";

  const inventory = ctx.player.inventory.length > 0
    ? ctx.player.inventory.map((i) => `  [${i.id}] ${i.name} (${i.tier})`).join("\n")
    : "  (empty)";

  const statusEffects = ctx.player.statusEffects.length > 0
    ? ctx.player.statusEffects.join(", ")
    : "none";

  const participants = ctx.allParticipants
    .map((p) => `  ${p.name}: ${p.hp} HP${p.statusEffects.length > 0 ? ` [${p.statusEffects.join(", ")}]` : ""}`)
    .join("\n");

  return `## Campaign: ${ctx.campaign.title}
${ctx.campaign.description}${history}

## Current Encounter
Monster: ${ctx.monster.name} (${ctx.monster.tier}) — ${ctx.monster.hp} HP remaining [${monsterCondition(ctx.monster.hp)}]
Monsters still to come after this one: ${ctx.monstersRemaining}${ctx.nextMonsterName ? `\nNext monster (reveal only if this one dies): ${ctx.nextMonsterName}` : "\nThis is the final monster."}

## Acting Player: ${ctx.player.name}
HP: ${ctx.player.hp}/100
Inventory:
${inventory}
Status effects: ${statusEffects}

## All Participants
${participants}

## This Turn
Dice rolls (use one per action step, in order):
${ctx.rolls.map((r, i) => `  Roll ${i + 1}: ${r.value}/100 (${r.descriptor})`).join("\n")}
Player action: ${ctx.playerAction}

Resolve this turn using the resolve_turn tool.`;
}

export async function resolveTurn(ctx: TurnContext): Promise<TurnResult> {
  const systemBlock: TextBlockParam & { cache_control?: CacheControlEphemeral } = {
    type: "text",
    text: GM_SYSTEM_PROMPT,
    cache_control: CACHE,
  };

  const response = await withTimeout(
    client.messages.create({
      model: "claude-haiku-4-5",
      max_tokens: 1024,
      system: [systemBlock],
      tools: [RESOLVE_TURN_TOOL],
      tool_choice: { type: "tool", name: "resolve_turn" },
      messages: [{ role: "user", content: buildTurnPrompt(ctx) }],
    }),
    30_000,
    "resolveTurn"
  );

  const toolUse = response.content.find((b) => b.type === "tool_use");
  if (!toolUse || toolUse.type !== "tool_use") throw new Error("GM did not use resolve_turn tool");

  const raw = toolUse.input as Record<string, unknown>;
  const rawAllyEffects = (raw["ally_effects"] as Array<Record<string, unknown>> | undefined) ?? [];
  const allyEffects: AllyEffect[] = rawAllyEffects.map((e) => ({
    playerName: String(e["player_name"] ?? ""),
    hpDelta: safeInt(e["hp_delta"], 0),
    statusEffectsAdded: (e["status_effects_added"] as string[] | undefined) ?? [],
    statusEffectsRemoved: (e["status_effects_removed"] as string[] | undefined) ?? [],
  })).filter((e) => e.playerName !== "");

  return {
    narrative: String(raw["narrative"] ?? "")
      .replace(/\\n/g, "\n")
      .replace(/<parameter[\s\S]*/i, "")
      .replace(/[,"'\s]+$/, "")
      .trim(),
    monsterHpDelta: safeInt(raw["monster_hp_delta"], 0),
    playerHpDelta: safeInt(raw["player_hp_delta"], 0),
    allyEffects,
    itemsConsumed: (raw["items_consumed"] as number[] | undefined) ?? [],
    incapacitationDurationMs: safeInt(raw["incapacitation_duration_ms"], 0),
    incapacitationReason: String(raw["incapacitation_reason"] ?? ""),
    statusEffectsAdded: (raw["status_effects_added"] as string[] | undefined) ?? [],
    statusEffectsRemoved: (raw["status_effects_removed"] as string[] | undefined) ?? [],
    unclearAction: Boolean(raw["unclear_action"] ?? false),
  };
}

export async function generateCampaign(
  recentSummaries: string[]
): Promise<{ title: string; description: string; monsters: GeneratedMonster[] }> {
  const summaryContext = recentSummaries.length > 0
    ? `Recent campaign history on Planet Gork:\n${recentSummaries.map((s, i) => `${i + 1}. ${s}`).join("\n")}\n\nThe new campaign should feel connected to and evolved from this history.`
    : "This is the first campaign on Planet Gork. Establish the world.";

  const seeds = pickSeeds();

  const prompt = `${summaryContext}

This campaign's random seeds — incorporate all of them:
${seeds}

Generate a new campaign. Include exactly 5 monsters in this order: 3 normal monsters, then 1 miniboss, then 1 boss. The monsters array must be ordered exactly as they will be encountered — boss last.

Monster naming format: "[Name] the [Adjective] [Type]" — more elaborate for minibosses and bosses.
Examples: "Gormuck the Strange Ork", "Tinkle Spork the Effeminate Space Ranger", "Grand Vizier Blortax the Infinitely Cursed Space Tyrant"

Use the generate_campaign tool.`;

  const response = await withTimeout(
    client.messages.create({
      model: "claude-haiku-4-5",
      max_tokens: 2048,
      tools: [GENERATE_CAMPAIGN_TOOL],
      tool_choice: { type: "tool", name: "generate_campaign" },
      messages: [{ role: "user", content: prompt }],
    }),
    60_000,
    "generateCampaign"
  );

  const toolUse = response.content.find((b) => b.type === "tool_use");
  if (!toolUse || toolUse.type !== "tool_use") throw new Error("GM did not use generate_campaign tool");

  const raw = toolUse.input as Record<string, unknown>;
  const monsters = (raw["monsters"] as Array<{ name: string; tier: string }> | undefined) ?? [];

  return {
    title: String(raw["title"] ?? "Untitled Campaign"),
    description: String(raw["description"] ?? ""),
    monsters: monsters.map((m) => ({
      name: m.name,
      tier: m.tier as MonsterTier,
    })),
  };
}

export async function generateLoot(
  monsterName: string,
  tier: string,
  counts: { mundane: number; special: number; exotic: number }
): Promise<GeneratedLoot[]> {
  const totalItems = counts.mundane + counts.special + counts.exotic;
  if (totalItems === 0) return [];

  const prompt = `The monster "${monsterName}" (${tier}) has been defeated in Tales of Planet Gork.

Generate ${totalItems} loot items:
- ${counts.mundane} mundane items
- ${counts.special} special items
- ${counts.exotic} exotic items

Loot names are absurd, specific, and creative. Format: [Adjective(s)] [Thing] of [Absurd Description].
Mundane examples: "Desk Lamp of Illumination", "Stolen Traffic Light of Crime"
Special examples: "Magic Odourous Tube Sock of Withering Disgust"
Exotic examples: "Crushing Lazer Grenade of Galahads Holy Ballsack", "One Day Blinding Stew of Powerful Piss Shivers"

Be original. Be weird. Planet Gork flavor.
Use the generate_loot tool.`;

  const response = await withTimeout(
    client.messages.create({
      model: "claude-haiku-4-5",
      max_tokens: 1024,
      tools: [GENERATE_LOOT_TOOL],
      tool_choice: { type: "tool", name: "generate_loot" },
      messages: [{ role: "user", content: prompt }],
    }),
    30_000,
    "generateLoot"
  );

  const toolUse = response.content.find((b) => b.type === "tool_use");
  if (!toolUse || toolUse.type !== "tool_use") throw new Error("GM did not use generate_loot tool");

  const raw = toolUse.input as Record<string, unknown>;
  const items = (raw["items"] as Array<{ name: string; tier: string }> | undefined) ?? [];

  return items.map((item) => ({
    name: item.name,
    tier: item.tier as LootTier,
  }));
}

export async function summarizeCampaign(
  title: string,
  description: string,
  turnHistory: Array<{ player_name: string; player_action: string; gm_narrative: string }>
): Promise<{ summary: string; closingNarrative: string }> {
  const historyText = turnHistory
    .map((t) => `${t.player_name}: ${t.player_action} → ${t.gm_narrative}`)
    .join("\n");

  const prompt = `A Planet Gork campaign has just ended. Write two things:

1. A compact 2-4 sentence summary for future campaign generation (factual continuity notes).
2. A dramatic 4-6 sentence closing paragraph for the players — celebrate what they did, give the ending weight.

Campaign: ${title}
${description}

What happened:
${historyText}

Use the summarize_campaign tool.`;

  const response = await withTimeout(
    client.messages.create({
      model: "claude-haiku-4-5",
      max_tokens: 768,
      tools: [SUMMARIZE_CAMPAIGN_TOOL],
      tool_choice: { type: "tool", name: "summarize_campaign" },
      messages: [{ role: "user", content: prompt }],
    }),
    30_000,
    "summarizeCampaign"
  );

  const toolUse = response.content.find((b) => b.type === "tool_use");
  if (!toolUse || toolUse.type !== "tool_use") throw new Error("GM did not use summarize_campaign tool");

  const raw = toolUse.input as Record<string, unknown>;
  return {
    summary: String(raw["summary"] ?? ""),
    closingNarrative: String(raw["closing_narrative"] ?? ""),
  };
}
